services:
  imgproxy:
    image: darthsim/imgproxy:latest
    env_file:
      - .env
    volumes:
      - ./sample_images:/app/sample_images
    stdin_open: true
    tty: true
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "10000:10000"
    depends_on:
      - imgproxy
  tool:
    image: golang:1.22-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./tool:/app
    profiles:
      - tool
